### ISSUE TITLE
Documentation outline

### ISSUE THREAD

**Issue by tamagokun** [fridge-cms/fridge-cms.github.io#1]
Pages probably needed:

* [x] Introduction
 * [x] What is Fridge?
 * [x] Content Types
 * [x] Concepts
* [x] Getting Started (focuses on going from sign-up to having a Fridge with content and possibly even a website)
 * [x] Create Content Type
 * [x] Create Content
 * [x] Fridge settings page (API Keys)
* [x] Webhooks (why webhooks? how to add webhooks. common use cases)
* [ ] User Roles (what they are good for. explaining permissions)
* [x] Content Part Reference
 * [x] Basic (text, number, color, content, wysiwyg)
 * [x] Relationships
 * [x] Files (file, image)
 * [x] Conditional (checkbox, dropdown, etc)
* [x] Content Type options (explain display options, API settings, email notification, public creation, etc)
* [x] API Libraries (just a list of libraries with links to Github)
* [ ] API Changelog (show API changes that take place)

**Comment by tamagokun** [comment]
@digmshift we don't even need all of this, the main intro/concepts/how tos are probably the most important.

The blog posts will cover a lot of the "getting started" stuff until we can flesh that out more.

**Comment by tamagokun** [comment]
All of the pages should be added here: https://github.com/fridge-cms/fridge-cms.github.io/tree/master/pages/docs

Just make a folder with the name of the page (slugged name), and then inside the folder create a `index.md` file, which is the content. You can copy/paste an existing page to get you going quicker.

**Comment by tamagokun** [comment]
Feel free to grab screenshots or what-not and drop them into the same folder as the markdown file and use them in there.

**Comment by digmshift** [comment]
Sweet! Sounds good.

**Comment by tamagokun** [comment]
Still lacking a "Users and User Roles" page, but I think this is fine for now.
