### ISSUE TITLE
Can't delete relationship fields

### ISSUE THREAD

**Issue by LairBob** [fridge-cms/fridge-cms.github.io#5]
Once I've defined a field as a "relationship", I don't seem to be able to delete it if I later decide I don't need it. I can change the type to something else, like "text", but if I delete it and try to click "Save", I never see the checkbox confirmation, and if I close "Edit Model" and re-open it, the field is still there.

**Comment by LairBob** [comment]
Aaand...it just worked. (Not sure if this was just getting lucky, or a prompt fix, but I'll let you know if I see it again -- leaving this open for now.)

**Comment by tamagokun** [comment]
I wonder if your auth token expired? I can't seem to replicate this.

**Comment by tamagokun** [comment]
I've figured out why this is happening, and have created an issue in the upstream repo for the front-end of the site :+1:

thanks!
